name: unruffled
description: Build offline first applications easily with Unruffled.
version: 1.11.0
homepage: https://github.com/tmilian/unruffled

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  dio: ^4.0.6
  hive: ^2.2.3
  get_it: ^7.2.0
  json_annotation: ^4.6.0
  meta: ^1.8.0
  recase: ^4.0.0
  socket_io_client: ^2.0.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.21.5
