name: unruffled
description: Build offline first applications easily with Unruffled.
version: 1.0.0
homepage: https://github.com/tmilian/unruffled

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  dio: ^4.0.6
  hive: ^2.1.0
  get_it: ^7.2.0
  isar: ^2.4.0
  json_annotation: ^4.5.0
  meta: ^1.7.0
  recase: ^4.0.0
  socket_io_client: ^1.0.2
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.10
  json_serializable: ^6.2.0
  lints: ^1.0.0
  test: ^1.16.0
