name: unruffled
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  dio: ^4.0.6
  hive: ^2.1.0
  recase: ^4.0.0
  socket_io_client: ^1.0.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
