name: unruffled_feathersjs
description: A FeathersJS client based on unruffled
version: 1.0.0
homepage: https://github.com/tmilian/unruffled/tree/master/unruffled_feathersjs

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  json_annotation: ^4.5.0
  unruffled: ^1.2.0

dev_dependencies:
  build_runner: any
  dio: ^4.0.6
  json_serializable: ^6.2.0
  unruffled_generator: ^1.1.0
  http_mock_adapter: ^0.3.2
  lints: ^1.0.0
  test: ^1.16.0
