name: unruffled_feathersjs
description: A FeathersJS client for Flutter based on unruffled
version: 1.11.0
homepage: https://github.com/tmilian/unruffled/tree/master/unruffled_feathersjs

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  get_it: ^7.2.0
  json_annotation: ^4.6.0
  meta: ^1.8.0
  socket_io_client: ^2.0.0
  unruffled: ^1.11.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  unruffled_generator: ^1.11.0
  http_mock_adapter: ^0.3.3
  lints: ^2.0.0
  test: ^1.16.0
