name: unruffled_feathersjs
description: A FeathersJS client for Flutter based on unruffled
version: 1.10.0
homepage: https://github.com/tmilian/unruffled/tree/master/unruffled_feathersjs

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  get_it: ^7.2.0
  json_annotation: ^4.5.0
  meta: ^1.7.0
  socket_io_client: ^1.0.2
  unruffled: ^1.9.0

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  unruffled_generator: ^1.8.0
  http_mock_adapter: ^0.3.2
  lints: ^1.0.0
  test: ^1.16.0
